name: Build and deploy ASP.Net Core + React to Azure Web App - FootballDojo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Setup Node for React
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: FootballDojo-UI
        run: npm install

      - name: Build React frontend
        working-directory: FootballDojo-UI
        run: npm run build

      # Copy React build to backend wwwroot
      - name: Copy React build to backend wwwroot
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path FootballDojo/wwwroot
          Copy-Item -Path FootballDojo-UI/dist/* -Destination FootballDojo/wwwroot -Recurse -Force

      # Setup .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore backend dependencies
        working-directory: FootballDojo
        run: dotnet restore

      - name: Build backend
        working-directory: FootballDojo
        run: dotnet build --configuration Release

      - name: Publish backend
        working-directory: FootballDojo
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: FootballDojo/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FootballDojo'
          slot-name: 'Production'
          package: ./app

    env:
      FOOTBALLDOJO_API_HOST: ${{ secrets.FOOTBALLDOJO_API_HOST }}
      FOOTBALLDOJO_API_KEY: ${{ secrets.FOOTBALLDOJO_API_KEY }}
