name: Build and deploy ASP.Net Core + React to Azure Web App - FootballDojo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Setup Node for React
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: FootballDojo.Client
        run: npm install

      - name: Build React frontend
        working-directory:FootballDojo.Client
        run: npm run build

      # Copy React build to backend wwwroot
      - name: Copy React build to backend wwwroot
        run: |
          mkdir -p ./FootballDojo.API/wwwroot
          cp -r ./FootballDojo.Client/dist/* ./FootballDojo.API/wwwroot/

      # Setup .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        working-directory: ./FootballDojo.API
        run: dotnet restore

      - name: Build backend
        working-directory: ./FootballDojo.API
        run: dotnet build --configuration Release

      - name: Publish backend
        working-directory: ./FootballDojo.API
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FootballDojo'
          slot-name: 'Production'
          package: ./${{env.DOTNET_ROOT}}/myapp

    env:
      FOOTBALLDOJO_API_HOST: ${{ secrets.FOOTBALLDOJO_API_HOST }}
      FOOTBALLDOJO_API_KEY: ${{ secrets.FOOTBALLDOJO_API_KEY }}
